# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - d-shp-func-esposter-auea-001

on:
  push:
    branches:
      - develop

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: packages/webhook

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v5

      - name: ğŸ”§ Setup Project Dependencies
        uses: ./.github/actions/setup-project-dependencies

      - name: ğŸ“¦ Resolve Project Dependencies
        run: |
          pushd ./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          pnpm i
          pnpm build
          popd

      - name: ğŸ“¦ Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: ğŸ“¤ Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: ğŸ“¥ Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: ğŸ—œï¸ Unzip artifact for deployment
        run: |
          unzip release.zip
          rm release.zip

      - name: â¬†ï¸ Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

      - name: ğŸš€ Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: d-shp-func-esposter-auea-001
          slot-name: Production
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A05B9C3CC0E447C58F4B5B8673600880 }}
