# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - d-shp-func-esposter-auea-001

on:
  push:
    branches:
      - develop

env:
  OUTPUT_DIRECTORY: dist

jobs:
  build-and-deploy:
    permissions:
      id-token: write # Require write permission to Fetch an OIDC token.

    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v5

      - name: ðŸ”§ Setup Project Dependencies
        uses: ./.github/actions/setup-project-dependencies

      - name: ðŸ“¦ Resolve Project Dependencies
        run: |
          echo "inject-workspace-packages=true" >> .npmrc
          echo "node-linker=hoisted" >> .npmrc
          pnpm --filter @esposter/webhook... i --no-frozen-lockfile
          pnpm --filter @esposter/webhook deploy ${{ env.OUTPUT_DIRECTORY }}

      - name: ðŸ”‘ Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ðŸ“¡ Get GitHub Runner IP
        id: get_ip
        run: echo runner_ip=$(curl -s ipinfo.io/ip) >> $GITHUB_OUTPUT

      - name: ðŸ“¡ Allow Runner IP in Azure Function App SCM Firewall
        run: |
          az functionapp config access-restriction add \
          --resource-group d-shp-rg-esposter-auea-001 \
          --name d-shp-func-esposter-auea-001 \
          --rule-name GitHub-Actions-${{ github.run_id }} \
          --action Allow \
          --ip-address ${{ steps.get_ip.outputs.runner_ip }}/32 \
          --priority 200 \
          --scm-site true

      - name: ðŸš€ Run Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: d-shp-func-esposter-auea-001
          package: ${{ env.OUTPUT_DIRECTORY }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE  }}
          respect-funcignore: true

      - name: ðŸ“¡ Remove Runner IP from Azure Function App SCM Firewall
        if: always() # This ensures the rule is removed even if deployment fails
        run: |
          az functionapp config access-restriction remove \
            --resource-group d-shp-rg-esposter-auea-001 \
            --name d-shp-func-esposter-auea-001 \
            --rule-name GitHub-Actions-${{ github.run_id }} \
            --scm-site true
