# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - d-shp-func-esposter-auea-001

on:
  push:
    branches:
      - develop

env:
  FUNCTION_APP_NAME: d-shp-func-esposter-auea-001
  OUTPUT_DIRECTORY: dist
  PACKAGE_PATH: packages/azure-functions
  RESOURCE_GROUP_NAME: d-shp-rg-esposter-auea-001
  STORAGE_ACCOUNT_NAME: dshpstespauea001
  ZIP_FILE_NAME: release.zip

jobs:
  build-and-deploy:
    permissions:
      id-token: write # Require write permission to Fetch an OIDC token.

    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v5

      - name: ðŸ”¨ Setup Project Dependencies
        uses: ./.github/actions/setup-project-dependencies

      - name: ðŸ”§ Resolve Project Dependencies
        run: |
          echo inject-workspace-packages=true >> .npmrc
          echo node-linker=hoisted >> .npmrc
          pushd ${{ env.PACKAGE_PATH }}
          pnpm --filter @esposter/azure-functions... i --no-frozen-lockfile
          pnpm --filter @esposter/azure-functions... build
          popd
          pnpm --filter @esposter/azure-functions deploy ${{ env.OUTPUT_DIRECTORY }}
          cp ${{ env.PACKAGE_PATH }}/host.json ${{ env.OUTPUT_DIRECTORY }}/host.json

      - name: ðŸ“¦ Zip Artifact for Deployment
        run: |
          pushd ${{ env.OUTPUT_DIRECTORY }}
          zip -r ../${{ env.ZIP_FILE_NAME }} . -x@.funcignore
          popd

      - name: ðŸ”‘ Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ðŸŒ Get GitHub Runner IP
        id: get_ip
        run: echo runner_ip=$(curl -s ipinfo.io/ip) >> $GITHUB_OUTPUT

      - name: ðŸ“¡ Allow Runner IP in Storage Account Firewall
        run: |
          az storage account network-rule add \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --ip-address ${{ steps.get_ip.outputs.runner_ip }}

      - name: ðŸš€ Upload Package to Blob Storage and Update App Settings
        run: |
          BLOB_NAME="${{ github.sha }}.zip"
          az storage container create --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --name ${{ env.FUNCTION_APP_NAME }} --auth-mode login
          az storage blob upload --account-name ${{ env.STORAGE_ACCOUNT_NAME }} --container-name ${{ env.FUNCTION_APP_NAME }} --name $BLOB_NAME --file ${{ env.ZIP_FILE_NAME }} --auth-mode login

          BLOB_URL="https://${{ env.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/${{ env.FUNCTION_APP_NAME }}/${BLOB_NAME}"
          az functionapp config appsettings set --name ${{ env.FUNCTION_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }} --settings "WEBSITE_RUN_FROM_PACKAGE=${BLOB_URL}"

      - name: ðŸ“¡ Remove Runner IP from Storage Account Firewall
        if: always() # This ensures the rule is removed even if deployment fails
        run: |
          az storage account network-rule remove \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --ip-address ${{ steps.get_ip.outputs.runner_ip }}
